export const APPLICATION_MOUNTING = 'APPLICATION_MOUNTING';
export const ROUTER_BOOTSTRAPPED = 'ROUTER_BOOTSTRAPPED';
export const FOO_CLICKED = 'FOO_CLICKED';
export const BAR_CLICKED = 'BAR_CLICKED';
